### ISSUE TITLE
PC and PP test data needed

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral.test#1]
See https://github.com/pharmaverse/admiral/issues/827 - need to use CDISC pilot DM data to create realistic synthetic data for PC and PP in {admiral.test} to allow {admiral} development of PK ADaMs.
Once we have this we could also share back with CDISC in case they want to add to their pilot data repository.

Note that personal data shouldn't be used for testing even if anonymised. One of my colleagues co-authored this useful paper recently on the topic: https://link.springer.com/article/10.1007/s44163-021-00016-y - it also gives lots of great advice on methods around synthetic data generation.

**Comment by toni-1991** [comment]
As per the discussion on https://github.com/pharmaverse/admiral/issues/602, it seems that the data provided, despite not perfect, it's good enough to program ADPC and ADPP, on a later stage we can revisit if needed and implement a few improvements.
[PK datasets.zip](https://github.com/pharmaverse/admiral.test/files/7992638/PK.datasets.zip)

**Comment by rossfarrugia** [comment]
Thanks @toni-1991 for your efforts! I linked the PR Mahdi created at https://github.com/pharmaverse/admiral.test/pull/8 with this issue so that it will automatically close once @thomas-neitmann reviews and merges to main.

**Comment by RealSlimMahdi** [comment]
Thanks, @toni-1991 and @rossfarrugia & @MichaelRimler for helping with this.

@toni-1991 as Ross mentioned, the PR is ready with PC. However it still needs PP, you can commit to the branch and it will automatically update the PR

**Comment by toni-1991** [comment]
Hi @RealSlimMahdi , I just added a commit to the branch with the PP data and PC and PP programs
