### ISSUE TITLE
Create SC for admiralophtha

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral.test#102]
See code: https://github.com/pharmaverse/admiralophtha/blob/devel/dev/sc.R

@bms63 Should SDTM.SC be called admiral_sc or admiralophtha_sc as it is Ophtha specific.

**Comment by bms63** [comment]
`admiralophtha_sc` seems pretty long to write out in code.  Maybe it should just be `admiral_sc` and we can make  a reference to the `admiralophtha` package in the documentation for the `admiral_sc` dataset? 

@rossfarrugia @bundfussr @thomas-neitmann  what do you all think?

Maybe we should also reference the `admiralonco` package in the `tr` dataset and any others-  just to help cross-reference our extension packages and create some buzz?

Guess we might want to document this in our readme as well i.e. reference extensions packages in SDTM datasets  if those datasets are specific for them

**Comment by bundfussr** [comment]
I would try to keep it simple and use the ``admiral_`` prefix for all datasets. For SC and AE.AELAT this should not cause any issues as these additions should not affect existing examples or templates.

**Comment by rossfarrugia** [comment]
Agree with Stefan! who knows when the SC might be needed for other TA extension packages in future too, so not necessarily ophtha specific.
