### ISSUE TITLE
Update readme instructions on updating sdtm data

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#106]
@bms63 @rossfarrugia I followed instructions in README file, but I can't generate the `.man` files, it ERRORs each time I run `devtools::document()`. The instructions are out of date, as the programs are in `dev` folder not `inst/dat_scripts`, so maybe there have been other changes?? Any guidance appreciated, thanks.

_Originally posted by @millerg23 in https://github.com/pharmaverse/admiral.test/issues/104#issuecomment-1408790555_

Definition of Done

- [ ] Instructions for updating sdtm datasets are updated and clear.
- [ ] A list of recommended packages to install `metatools`, `labelled` others for development work
- [ ] A brief rationale on why we don't include these packages in DESCRIPTION file or renv.lock

**Comment by bms63** [comment]
Hey @millerg23 anything you want to add?

**Comment by millerg23** [comment]
Just that the `devtools::document()` only fails when I try to add `raw_ae`. otherwise it runs fine.

**Comment by bms63** [comment]
@bundfussr and @rossfarrugia anything else we want to add - sorry this one is a little rough.
