### ISSUE TITLE
Create news entry linking onco and ophtha packages and data specific to them

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#114]
We could put a blurb in the news that admiral.test has sdtm data for oncology and opthat available and link to pkgdown sites.  I'll make an issue to do this before the release.

_Originally posted by @bms63 in https://github.com/pharmaverse/admiral.test/pull/113#discussion_r1101869228_

**Comment by zdz2101** [comment]
@bms63 I can work on this news update alongside #109 but I don't have access to the repo

**Comment by bms63** [comment]
Added
