### ISSUE TITLE
Decide whether to Remove `library(admiral.test)` from Programs in `dev/` Directory

### ISSUE THREAD

**Issue by fshanlee** [pharmaverse/admiral.test#122]
Please make a decision regarding comment https://github.com/pharmaverse/admiral.test/pull/115#issuecomment-1438562855.

Maybe we should avoid specifying `library(admiral.test)` at the start of any program in the `dev/` directory: if a program needs to read a dataset from {admiral.test}, then read it directly from the `data/` directory in the repo, rather than reference it via the previously built package.

**Comment by bms63** [comment]
Good point @fshanlee .  That could maybe be a little dangerous.  Any thoughts @pharmaverse/admiral.  

@fshanlee has been updating instructions on writing and maintaining our test scripts.  Has brought up some good discussion in #115

**Comment by bms63** [comment]
Duplicate issue #123
