### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#149]
@pharmaverse/admiral Any objections to me archiving this repo now that pharmaversesdtm is available?

**Comment by zdz2101** [comment]
Considering we already say it in the `README` I think you can proceed

**Comment by bms63** [comment]
![image](https://github.com/pharmaverse/admiral.test/assets/10111024/a0137010-be2e-4c6a-900c-f0b664c57f69)

![image](https://github.com/pharmaverse/admiral.test/assets/10111024/b71716a1-9f58-4dd9-85cf-2f1f3fc99f27)
