### ISSUE TITLE
Address CRAN comments

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral.test#16]
> Thanks,
Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: {admiral}--> 'admiral'
Please add some more details about the package functionality and
implemented methods in your Description text.
Please always explain all acronyms in the description text.
Please ensure that your functions do not write by default or in your
examples/vignettes/tests in the user's home filespace (including the
package directory and getwd()). This is not allowed by CRAN policies. In
your examples/vignettes/tests you can write to tempdir().
e.g. inst/data_scripts/query_databases.R
Please fix and resubmit.
Best,
Julia Haider

**Comment by thomas-neitmann** [comment]
@bundfussr Could you take a look at the issue mentioned in the last paragraph?

**Comment by bundfussr** [comment]
@thomas-neitmann , I am not sure how we should fix the last comment. The purpose of query_databases.R is to write to the data folder. It is the source code of the pseudo query databases and enable us to recreate and change them if needed.

Was the same comment raised for admiral? The template scripts work in the same way.

**Comment by thomas-neitmann** [comment]
{admiral} itself did not make it to the manual review step, yet, so that comment was not raised. But I'm sure it will be once we pass the initial automated checks. I remember getting the same kind of comments when submitting another package in the past. I would probably just delete the last line in the script and whenever the data needs to e updated one has to run this one line manually in the R console.

**Comment by thomas-neitmann** [comment]
Alterntively, we could move the script to `.Rbuildignore` such that is gets excluded when building the package. It's not meant for users anyway so I'd probably prefer this approach.

**Comment by bundfussr** [comment]
Thanks, I prefer the second approach, too.

**Comment by bundfussr** [comment]
@thomas-neitmann , I have added the change to your pull request.
