### ISSUE TITLE
TU, TR, and RS test data needed

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral.test#2]
See pharmaverse/admiral#827 - need to use CDISC pilot DM data to create realistic synthetic data for oncology SDTM domains (TU, TR, and RS) in {admiral.test} to allow {admiral.onco} oncology specific package extension development of Onco efficacy ADaMs (ADRS and ADTTE). 
Once we have this we could also share back with CDISC in case they want to add to their pilot data repository.

Note that personal data shouldn't be used for testing even if anonymised. One of my colleagues co-authored this useful paper recently on the topic: https://link.springer.com/article/10.1007/s44163-021-00016-y - it also gives lots of great advice on methods around synthetic data generation.

**Comment by rossfarrugia** [comment]
Gopi from Astellas has agreed to take this on and I'll assign him once accepted as a member of the org

**Comment by Gopi2345** [comment]
Thank you Ross.

**Comment by Gopi2345** [comment]
@bundfussr, Thank you, I updated tu, tr and rs scripts by adding dataset labels.
