### ISSUE TITLE
Add SV dataset

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral.test#20]
- Download dataset from [here](https://bitbucket-test.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm)
- Read into R using `haven::read_xpt()`
- Save into the `data` folder using `save(sv, file = "data/sv.rda", compress = "bzip2")`

**Comment by sophie-gem** [comment]
@thomas-neitmann I'd be happy to take this one - would be a good first contribution for me.

**Comment by thomas-neitmann** [comment]
Awesome, thank you so much @sophie-gem 🎉

**Comment by thomas-neitmann** [comment]
I just added you to the repo. Please take a look at our admiral dev guides (on the website) regarding processes etc. In case of any question just let me know.

**Comment by sophie-gem** [comment]
Will do. Thanks very much!
