### ISSUE TITLE
Add supplb 

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#24]
Working on the [`adlb`](https://github.com/pharmaverse/admiral/pull/998) script.  Is it possible for us to include one of the supp lab datasets in the CDISC pilot study?  Then we can showcase `metatools::derive_vars_suppqual() ` in the example.

@statasaurus, @thomas-neitmann, @rossfarrugia, @millerg23.  What do you all think?

I know there is a few to choose from.

![image](https://user-images.githubusercontent.com/10111024/161825421-bdc38c1a-4740-4048-bcec-813a5cad7cb8.png)

**Comment by rossfarrugia** [comment]
@bms63 my thinking was we were going to take all reference of merging suppquals out of any admiral vignettes, as it's not really related to ADaM derivations themselves, it's more a preprocessing step. So @statasaurus was then going to cover this in the end-to-end ADaM vignettes for pharmaverse where i think i remember she's using https://cran.r-project.org/web/packages/safetyData/index.html as test data input anyway which already has SUPPxx. 

I'll let Christina confirm though and potentially close this issue if not needed.

**Comment by rossfarrugia** [comment]
Also just a reminder that for admiral we don't want to implicitly make metatools a dependency, as some companies will use both and others may only use admiral.

**Comment by rossfarrugia** [comment]
Will close this issue as if the e2e vignettes ever use admiraltest in future then we could use one of the other SUPP examples that already exist here for this. We can re-open this issue in future if we ever find a definite need for this.

**Comment by bms63** [comment]
Ohhh... we still might want this for the adlb script.  We are meeting next week to discuss
