### ISSUE TITLE
Add RANDOMIZATION records to DS

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral.test#35]
Add new dummy disposition event records with DSTERM and DSDECOD = "RANDOMIZED" for each patient and for dates it's fine to use those from DM.RFSTDTC.

We need some dummy data here to feed through to admiral so that we can create an ADSL.RANDDT which can in turn be used for admiralonco and further TA-specific package extensions where things like time to event endpoints often are calculated using randomization date.

**Comment by rossfarrugia** [comment]
@Gopi2345 good question! if you look in the latest devel branch you'll see we recently made an update to all the datasets in `data/` folder to now have the `admiral_` prefix. for your change i would recommend you update https://github.com/pharmaverse/admiraltest/blob/main/R/data.R to take out the sourcing of DS from CDISC pilot and instead add this to your new code - which you could call R/ds.R.

i.e. cut and paste this section into your code:
```
#' Disposition Dataset
#'
#' A SDTM DS dataset from the CDISC pilot project
#'
#' @source \url{https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/ds.xpt}
"ds"
```

Then you can update the dataset accordingly and output to data/admiral_ds.rda.

Hope this makes sense but let me know if not.

**Comment by rossfarrugia** [comment]
@Gopi2345 we don't usually close issues until the commits are merged to main as part of a release. This way they are left open for transparency so no user raises the same issue again. We also don't need to manually close these, as by using the keywords at the start of the PR once we merge that to main then this issue will automatically close.

**Comment by Gopi2345** [comment]
Got it. Thank you for explaining and reopening.
