### ISSUE TITLE
Add variables to mh for admiral template script and dataset

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#51]
To make `admiral_admh` dataset and template script more interesting and complex within the `admiral `package we need to add variables to the sdtm dataset `mh`.  

At the moment we need the following variables could be added:
`MHOCCUR`
`MHENDTC`
`MHENRF`
`MHENTPT`

**Comment by bms63** [comment]
@yangc71

**Comment by yangc71** [comment]
@rossfarrugia / @bms63 I was trying to work on this but I couldn't create a branch, could you please grant me write access to admiral.test? Thanks.

**Comment by rossfarrugia** [comment]
@yangc71 now granted, and check out this PR https://github.com/pharmaverse/admiral.test/pull/55 for the new guidance on how to go about making this update.

**Comment by rossfarrugia** [comment]
@yangc71 are you ok to add these and make another PR?

**Comment by yangc71** [comment]
Thanks @rossfarrugia I added the two variables in MH. @gg106046 / @bms63 I haven't used those variables before, and I understand we are adding them to help derive the GSK AHIST variable downstream. Could you please help review to see if I added the variables properly? Thanks!
