### ISSUE TITLE
lb update for percent differentials for certain lab tests

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#52]
We will use this in our ad_adlb script.

https://github.com/pharmaverse/admiral/blob/main/R/derive_param_wbc_abs.R

**Comment by bms63** [comment]
All patients right only have absolute values - lets just update some of those existing values to what we need rather than create new observations.

**Comment by bms63** [comment]
See [admiral.test](https://github.com/pharmaverse/admiral.test/tree/devel)/[inst](https://github.com/pharmaverse/admiral.test/tree/devel/inst)/[data_scripts](https://github.com/pharmaverse/admiral.test/tree/devel/inst/data_scripts)/update_ds.R for some guidance

**Comment by bms63** [comment]
```
# A tibble: 11 × 6
   USUBJID PARAMCD  AVAL PARAM                       VISIT         DTYPE      
   <chr>   <chr>   <dbl> <chr>                       <chr>         <chr>      
 1 P01     WBC     33    Leukocyte Count (10^9/L)    CYCLE 1 DAY 1 NA         
 2 P01     WBC     38    Leukocyte Count (10^9/L)    CYCLE 2 DAY 1 NA         
 3 P01     LYMLE    0.9  Lymphocytes (fraction of 1) CYCLE 1 DAY 1 NA         
 4 P01     LYMLE    0.7  Lymphocytes (fraction of 1) CYCLE 2 DAY 1 NA         
 5 P01     ALB     36    Albumin (g/dL)              CYCLE 2 DAY 1 NA         
 6 P02     WBC     33    Leukocyte Count (10^9/L)    CYCLE 1 DAY 1 NA         
 7 P02     LYMPH   29    Lymphocytes Abs (10^9/L)    CYCLE 1 DAY 1 NA         
 8 P02     LYMLE    0.87 Lymphocytes (fraction of 1) CYCLE 1 DAY 1 NA         
 9 P03     LYMLE    0.89 Lymphocytes (fraction of 1) CYCLE 1 DAY 1 NA         
10 P01     LYMPH   29.7  Lymphocytes Abs (10^9/L)    CYCLE 1 DAY 1 CALCULATION
11 P01     LYMPH   26.6  Lymphocytes Abs (10^9/L)    CYCLE 2 DAY 1 CALCULATION
```

Hey @yangc71 and @millerg23  This is the output from the `derive_param_wbc_abs` example.  Is USUBJID P02 also supposed to have a Calculation done for them?

Also, I'm a little confused on my notes.  Can you tell me again what we were updating here?  In my notes, I just have update existing values for WBC, but that is it!  Looking at the data and this example just makes me a litte more confused :( sorry!  Please more guidance...tyty!

**Comment by bms63** [comment]
Thanks @millerg23.  I still like to try and make this update with your guidance!

**Comment by millerg23** [comment]
To keep things simple for the newly created Percent Differential lab tests, just set the variables holding the original results to the SI (standard unit) results. ie once LBSTRESN created, then set LBORRES = LBSTRESC. Likewise LBORRESU with LBSTRESU, LBORNRLO/LBORNRHI with LBSTNRLO/LBSTNRHI.
@bms63 if you let me know what lab tests you decide to choose, I can supply reasonable normal ranges to you.

**Comment by bms63** [comment]
LYM - Reference Ranges
lbstresu = "10^9/L";
    __rrlo   = 1;
    __rrhi   = 4.8;
