### ISSUE TITLE
Spec files need to be added for use for the pharmaverse e2e vignettes

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral.test#54]
Add dummy SDTM spec files to accompany our test data. See define file given with the CDISC pilot data.

Needs to be in a metacore compatible format.

Updates will be needed for the updates we've made to the CDISC pilot data so far and this process should be detailed in the README, so that anyone adding/updating the test data will know to also update the specs.

**Comment by rossfarrugia** [comment]
@statasaurus @bms63 - would it be worth one of you picking up the first stab on this one and then I'm happy to make the updates in line with the {admiral.test} updates we've made? As you guys know better what metacore expects here.

**Comment by bms63** [comment]
I'm not sure I have the time.  Can we call out for help to the general chat?

**Comment by rossfarrugia** [comment]
Yes sure, if one of you could add more detailed requirements to this issue then it could be opened up to others to contribute. i think it would need to be someone that knows metacore well. or this could be an area for @amitjaingsk to support us for enabling the e2e vignettes, but he might need some guidance from @statasaurus.

**Comment by statasaurus** [comment]
I am happy to help. You can use the p21_mock that is in the example of metacore if you want a reference

**Comment by rossfarrugia** [comment]
thanks @statasaurus - appreciate if you get chance around your conference this week to speak with @amitjaingsk and show a bit more of an intro on what's needed, and then the 3 of us can catch up more next week at the call i set up Weds 22nd

**Comment by rossfarrugia** [comment]
i think this one can close as admiral.test is being retired and we never got around to this. will try and pick something back up with the new examples site we plan to put time into after all the conferences later this year.
