### ISSUE TITLE
Move updating scripts to dev folder

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#62]
To keep package lean and mean and just focused on data, we have decided to move the data scripts that alter and update the CDSIC pilot data to a `dev` folder.

- The `dev` folder will also allow us to remove the dependency that exists for `metatools::add_labels()` and any other dependencies that might be needed in the future for updates.

DoD:  `dev` folder has been created and scripts moved and folder registered in `.Rbuildignore`

Concerns:  
* How to ensure that the code is written to a certain standard?

**Comment by thomas-neitmann** [comment]
Make sure that this `dev` folder is listed in `.Rbuildignore` such that it won't be included when building the package and shipping to CRAN.

**Comment by bms63** [comment]
I see we are just doing `.Rbuildignore` with `inst/templates` .  Shall we consider this done or do we want to make the `dev` folder?

**Comment by thomas-neitmann** [comment]
When we move the functions back into the `R` folder we'll have to re-list the dependency packages in the `DESCRIPTION` file. However, we wanted {admiral.test} to be dependency free. Thus, my suggestion would be to `source()` the function directly from GitHub in the affected {admiral} examples.

**Comment by bms63** [comment]
Can we move to `get_terms` to admiral or rebuild with base R?

**Comment by bms63** [comment]
i think we are just trying to make `admiral.test` a data package.   The updating of the test data means we have more scripts and need more packages to make those updates.  Moving all of them to a dev folder cuts out those dependencies.  

However, we may need to rethink it a a bit.  @thomas-neitmann

**Comment by thomas-neitmann** [comment]
We could indeed rewrite the function to only use base R functionality. From my quck glance at the function that shouldn't be too difficult.

However, since this is really only an example function it doesn't really feel like a correct approach to have it as an exported function in {admiral.test}.

That leaves moving the function over to {admiral} itself. We could put it directly in the example section for `derive_vars_query()` with a comments above that this is an example function and that user would have to define somethig similar for themselves.

**Comment by thomas-neitmann** [comment]
Alright, then let's keep the function in {admiral.test}. I'll make some small updates to get rid of the {dplyr} functions used in the function such that we can stick to the no-dependency strategy for {admiral.test}.

**Comment by bundfussr** [comment]
@thomas-neitmann , could you fix it? The issue is preventing us from merging any PRs in admiral.

**Comment by thomas-neitmann** [comment]
Working on it right now.
