### ISSUE TITLE
pc and pp datasets are missing labels

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#77]
These datasets need labels added

This dataset is missing labels.  Do we want to put labels on them or wait till next release?

_Originally posted by @bms63 in https://github.com/pharmaverse/admiral.test/issues/76#issuecomment-1232994184_

**Comment by PoojaKumari05** [comment]
@bms63 - I can take this issue but not able to assign myself. Could you help or let me know if there is something I am missing here?

**Comment by bms63** [comment]
Thanks @PoojaKumari05  I just had to add you to the repo

**Comment by PoojaKumari05** [comment]
> Thanks @PoojaKumari05 I just had to add you to the repo

Thankyou @bms63 :)
