### ISSUE TITLE
`{metatools}::add_labels` in dev script files

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral.test#87]
@thomas-neitmann What do you think about using `add_labels` from `{metatools}` rather than the `labelled::set_variable_labels` in all our dev scripts?

Could be a good first issue

**Comment by thomas-neitmann** [comment]
Does that require an metacore object to work?

**Comment by bms63** [comment]
It does not - actually pretty similar to labelled::set_variable_labels, but you know trying to keep it in the family :)

**Comment by thomas-neitmann** [comment]
I'll leave the decision up to you 🙂

**Comment by SyedMubasheer** [comment]
@bms63 I can pick this issue. Could you please assign it to me as I'm unable to assign myself or am I missing something?

**Comment by bms63** [comment]
Assigned and add your to this repo.

**Comment by SyedMubasheer** [comment]
> Assigned and added you to this repo.

Thank you @bms63 !!
