### ISSUE TITLE
Add AELAT to AE SDTM for admiralophtha

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral.test#99]
admiralophtha have created AE.AELAT variable and want it added to `admiral.test`
See code https://github.com/pharmaverse/admiralophtha/blob/devel/dev/ae.R

@bms63 I was thinking to just add this to `admiral_ae` however ophtha team think AELAT is Ophtha specific and maybe data set should be `admiralophtha_ae`. What do you think?

**Comment by bms63** [comment]
Oh ...Just seeing this one after commenting on the sc issue.  

@rossfarrugia @bundfussr @thomas-neitmann Maybe we should just have admiralophtha_xx, but just seems so long to write out.  Still think we should link out ot the package in the dataset documentation.

**Comment by rossfarrugia** [comment]
As per reply in other issue, i think fine to add this to `admiral_ae`
